from __future__ import annotations

from .hints import extract_cmd, os_family
from .models import Finding


def generate_fix_script(findings: list[Finding]) -> str:
    """Build a platform-appropriate fix script from actionable findings."""
    fam = os_family()
    is_win = fam == "windows"

    lines: list[str] = []
    if is_win:
        lines.append("# PowerShell fix script generated by skill-deps-doctor")
        lines.append("# Review carefully before running!\n")
    else:
        lines.append("#!/usr/bin/env bash")
        lines.append("set -euo pipefail")
        lines.append("# Fix script generated by skill-deps-doctor")
        lines.append("# Review carefully before running!\n")

    has_auto = False
    for f in findings:
        if f.severity == "info" or f.fix is None:
            continue
        cmd = extract_cmd(f.fix)
        lines.append(f"# [{f.severity.upper()}] {f.item}: {f.detail}")
        if cmd:
            if is_win:
                cmd = _to_powershell(cmd)
            lines.append(cmd)
            has_auto = True
        else:
            lines.append(f"# (manual) {f.fix}")
        lines.append("")

    if not has_auto:
        lines.append("echo 'No automated fixes available. See comments above.'")

    return "\n".join(lines) + "\n"


def _to_powershell(cmd: str) -> str:
    """Best-effort transform of a bash command to PowerShell equivalent."""
    if cmd.startswith("sudo apt-get"):
        return f"# Linux only: {cmd}"
    if cmd.startswith("sudo "):
        return f"# Linux only: {cmd}"
    if cmd.startswith("brew "):
        return f"# macOS only: {cmd}"
    return cmd
